# Set this correctly please..;-)
DOTFILES_HOME=$HOME/.dotfiles

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="dracula"
# ZSH_THEME=powerlevel10k/powerlevel10k

## Add the custom Cloud icon prompt segment
## Add kube-ps1
# KUBE_PS1_PREFIX=''
# KUBE_PS1_SUFFIX=''
# POWERLEVEL9K_CONTEXT_TEMPLATE="anand@macbook"
# POWERLEVEL9K_CUSTOM_KUBE_PS1='kube_ps1'
# POWERLEVEL9K_CUSTOM_KUBE_PS1_BACKGROUND="black"
# POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir vcs)
# POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status custom_kube_ps1)
# POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
# POWERLEVEL9K_STATUS_VERBOSE=false
# POWERLEVEL9K_SHORTEN_STRATEGY="truncate_middle"
# POWERLEVEL9K_SHORTEN_DIR_LENGTH=3

## Load Nerd Fonts with Powerlevel9k theme for Zsh
# POWERLEVEL9K_MODE='nerdfont-complete'
# ZSH_THEME="powerlevel9k/powerlevel9k"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git macosx zsh-autosuggestions zsh-syntax-highlighting)

# Would you like to use another custom folder than $ZSH/custom?
ZSH_CUSTOM=$DOTFILES_HOME/zsh
DISABLE_MAGIC_FUNCTIONS=true
source $ZSH/oh-my-zsh.sh
# export PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin"
# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Kube PS1 configurations
# KUBE_PS1_CTX_COLOR="black"
# KUBE_PS1_NS_COLOR="blue"
# KUBE_PS1_SYMBOL_COLOR="blue"
# KUBE_PS1_CTX_COLOR="yellow"
# KUBE_PS1_SYMBOL_USE_IMG="true"
# source "$HOME/.kube-ps1/kube-ps1.sh"
# kubeon

# Starship CLI Prompt
eval "$(starship init zsh)"
autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /usr/local/bin/bitcomplete bit

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/Users/anasharm/.sdkman"
[[ -s "/Users/anasharm/.sdkman/bin/sdkman-init.sh" ]] && source "/Users/anasharm/.sdkman/bin/sdkman-init.sh"
