## Bashrc

# Basic Environment variables
export EDITOR='vim'
export PATH="/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin"
export PATH=$PATH:$HOME/bin

# Aliases
alias ls='ls --color=auto'
alias c='clear'
alias g='git'
alias k='kubectl'
alias kx='kubectx'
alias kn='kubens'
alias s="stern"
alias p='python3'
alias p2='python2'
alias pipup='pip3 freeze --local | grep -v '^\-e' | cut -d = -f 1  | xargs pip3 install -U'
alias d='docker'
alias dm='docker-machine'
alias a='ansible'
alias ap='ansible-playbook'
alias tf='terraform'
alias t='tmux'

# Get the terminal ready
clear

# Colorful PS1
export PS1="\e[0;36m[\u@\h \W]\$ \e[m "

# Set this correctly please..;-)
DOTFILES_HOME=$HOME/.dotfiles
cat $DOTFILES_HOME/misc/om
w

